set(LEXACTIVATOR_BINARY_DIR "${CMAKE_CURRENT_BINARY_DIR}/../LexActivator")

set(LEXACTIVATOR_INCLUDE_DIR ${LEXACTIVATOR_BINARY_DIR}/include)
set(LEXACTIVATOR_LIB ${LEXACTIVATOR_BINARY_DIR}/libLexActivator_Chronos.a)
