set(PARMETIS_BINARY_DIR "${CMAKE_CURRENT_BINARY_DIR}/../parmetis")

set(METIS_LIB            ${PARMETIS_BINARY_DIR}/libmetis.a)
set(PARMETIS_LIB         ${PARMETIS_BINARY_DIR}/libparmetis.a)
set(PARMETIS_INCLUDE_DIR ${PARMETIS_BINARY_DIR}/include)


