if(NOT IS_ABSOLUTE ${CHRONOS_BINARY_DIR})
   set(CHRONOS_BINARY_DIR "${CMAKE_CURRENT_BINARY_DIR}/${CHRONOS_BINARY_DIR}")
endif()
set(CHRONOS_LIBRARIES   ${CHRONOS_BINARY_DIR}/lib/libChronos.a)
set(CHRONOS_INCLUDE_DIR ${CHRONOS_BINARY_DIR}/include)

